<?php 
/**
 * AmanCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@amancms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2010-2012 KhanSoft Limited (http://www.khansoft.com)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: list.phtml 5370 2010-09-09 16:20:43Z mehrab $
 * @since		1.0.0
 */
?>
<!-- Upload new widget -->
<?php if ($this->allow('upload')) : ?>
<div class="box grid_8 round_all clearfix">
	<h2 class="box_head"><?php echo $this->translator('widget_list_upload_head'); ?></h2>
	<div class="controls">
	    <a class="toggle" href="#">&nbsp;</a>
	</div>
	<div class="block">
		<div class="section">
			<?php if (extension_loaded('zip')) : ?>
			<form method="post" action="<?php echo $this->url(array(), 'core_widget_upload'); ?>" enctype="multipart/form-data">
				<p><?php echo $this->translator('widget_list_upload_desc'); ?></p>
				<input type="file" name="file" />
				
				<button type="submit" class="button_colour round_all"><span><?php echo $this->translator('widget_list_upload_button'); ?></span></button>
			</form>
			<?php else : ?>
			<div class="t_a_ui_helper_message"><?php echo $this->translator('widget_list_zip_extension_not_available'); ?></div>
			<?php endif; ?>
		</div>
	</div>
</div>
<?php endif; ?>

<div class="clearfix" ></div>

<!-- List of widgets group by module -->
<?php if ($this->widgets) : ?>
<div class="box grid_16 round_all">
	<h2 class="box_head"><?php echo $this->translator('widget_list_top_desc'); ?></h2>
	<div class="controls">
	    <a class="toggle" href="#">&nbsp;</a>
	</div>
	<div class="block">
    	<div class="box grid_15 round_all tabs">
    		<div class="side_holder">
    			<ul class="tab_sider clearfix" id="moduleFilter">
    			<?php foreach ($this->modules as $index => $module) : ?>
    				<li<?php //if (0 == $index) : ?> class="t_a_ui_active"<?php //endif; ?>><a href="#tabs-<?php echo $index; ?>"><?php echo $module; ?></a></li>
    				<?php endforeach; ?>
    			</ul>
    		</div>
    		
    		<?php $tabIndex=0;?>		
    		<?php foreach ($this->widgets as $module => $widgets) : ?>
    		<div id="tabs-<?php echo $tabIndex++;?>" class="block tab_sider">
    			<?php foreach ($widgets as $index => $widget) : ?>
    			<div class="content grid_5<?php if(($index+1)%3==1): echo ' alpha'; elseif(($index+1)%3==0): echo ' omega'; endif;?>">
    				<h2><?php echo $widget->name; ?></h2>
    				<span>
    					<?php if (isset($this->dbWidgets[strtolower($widget->module . ':' . $widget->name)])) : ?>
    					<a class="btn ui-state-default installAction" rel="<?php echo $this->dbWidgets[strtolower($widget->module . ':' . $widget->name)]; ?>" href="javascript: void(0);">
    						<span class="ui-icon ui-icon-circle-close"></span>
    						<?php echo $this->translator('widget_list_uninstall'); ?>
    					</a>
    					<?php else : ?>
    					<a class="btn ui-state-default installAction" rel="<?php echo strtolower($widget->module . ':' . $widget->name); ?>" href="javascript: void(0);">
    						<span class="ui-icon ui-icon-circle-plus"></span>
    						<?php echo $this->translator('widget_list_install'); ?>
    					</a>
    					<?php endif; ?>
    				</span>
    				<p>		
    					<?php echo $this->translator('widget_list_version'); ?>: <?php echo $widget->version; ?>
    					<?php echo $this->translator('widget_list_author'); ?>: <a href="mailto:<?php echo $widget->email; ?>"><?php echo $widget->author; ?></a>
    					<?php echo $widget->description; ?>
    				</p>
    			
    			</div>
    			<?php endforeach;?>	
    		</div>
    		<?php endforeach;?>    		
    		
    	</div>
    </div>
</div>
<?php endif;?>
	<div class="clear"></div>
	

<!-- Side Bar -->
<div id="sidebar">
	<div class="sidebar-content">
		<a id="close_sidebar" class="btn ui-state-default full-link ui-corner-all" href="#drill">
					<span class="ui-icon ui-icon-circle-arrow-e"></span>
					Close Sidebar
				</a>
		<a id="open_sidebar" class="btn tooltip ui-state-default full-link icon-only ui-corner-all" title="Open Sidebar" href="#"><span class="ui-icon ui-icon-circle-arrow-w"></span></a>
		<div class="hide_sidebar">
			
			<div class="portlet ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
				<div class="portlet-header ui-widget-header"><?php echo $this->translator('widget_list_filter_module'); ?>
					<span class="ui-icon ui-icon-circle-arrow-s"></span>
				</div>
				<div class="portlet-content">
					<ul class="side-menu" id="moduleFilter">
						<?php foreach ($this->modules as $index => $module) : ?>
						<li<?php if (0 == $index) : ?> class="t_a_ui_active"<?php endif; ?>><a href="javascript: void(0);"><?php echo $module; ?></a></li>
						<?php endforeach; ?>
					</ul>
				</div>
			
			</div>
		
			<ul class="side-menu">					                
                <?php if ($this->routeAccessor('core_module_list')) : ?>
				<li><a href="<?php echo $this->url(array(), 'core_module_list'); ?>"><?php echo $this->translator('menu_module', 'core'); ?></a></li>
				<?php endif; ?>
				
                <?php if ($this->routeAccessor('core_plugin_list')) : ?>
				<li><a href="<?php echo $this->url(array(), 'core_plugin_list'); ?>"><?php echo $this->translator('menu_plugin', 'core'); ?></a></li>
				<?php endif; ?>
                
                <?php if ($this->routeAccessor('core_widget_list')) : ?>
				<li><a href="<?php echo $this->url(array(), 'core_widget_list'); ?>"><?php echo $this->translator('menu_widget', 'core'); ?></a></li>
				<?php endif; ?>
                
                <?php if ($this->routeAccessor('core_hook_list')) : ?>
				<li><a href="<?php echo $this->url(array(), 'core_hook_list'); ?>"><?php echo $this->translator('menu_hook', 'core'); ?></a></li>
				<?php endif; ?>
                
                <?php if ($this->routeAccessor('core_target_list')) : ?>
				<li><a href="<?php echo $this->url(array(), 'core_target_list'); ?>"><?php echo $this->translator('menu_target', 'core'); ?></a></li>
				<?php endif; ?>
			</ul>
		</div>
	</div>
	
</div>
<!-- End Side Bar -->
<div class="clear"></div>

<div id="messageDialog"></div>

<script type="text/javascript">
//<![CDATA[
$(document).ready(function() {
		
	/**
	 * Install/Uninstall handler
	 */
	$('a.installAction').click(function() {
		var self = this;
		var arr  = $(self).attr('rel').split(':');
		$(self).html('').addClass('t_a_ui_helper_loading');
		switch (arr.length) {
			case 2:
				<?php if ($this->allow('install')) : ?>
				$.ajaxq('widget_list', {
					url: '<?php echo $this->url(array(), 'core_widget_install'); ?>',
					type: 'POST',
					data: { mod: arr[0], name: arr[1] },
					success: function(response) {
						$(self).attr('rel', response)
							.removeClass('t_a_ui_helper_loading')
							.append("<span class='ui-icon ui-icon-circle-close' /> <?php echo $this->translator('widget_list_uninstall'); ?>");
						$(self).parents('.widget').addClass('installed').removeClass('notinstalled');
						$('#messageDialog').html(sprintf('<?php echo addslashes($this->translator('widget_list_install_success')); ?>', arr[1], arr[0]))
							.dialog({
								title: '<?php echo addslashes($this->translator('common_dialog_message')); ?>',
								dialogClass: 't_a_ui_dialog',
								modal: true,
						    	show: { effect: 'fade' },
								open: function(event, ui) {
									setTimeout(function() {
										$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
									}, 3000);
								}
							});
					}
				});	
				<?php endif; ?>			
				break;
			case 3:
				<?php if ($this->allow('uninstall')) : ?>
				$.ajaxq('widget_list', {
					url: '<?php echo $this->url(array(), 'core_widget_uninstall'); ?>',
					type: 'POST',
					data: { mod: arr[0], name: arr[1], id: arr[2] },
					success: function(response) {
						$(self).attr('rel', response)
							.removeClass('t_a_ui_helper_loading')
							.append('<span class="ui-icon ui-icon-circle-plus" /><?php echo $this->translator("widget_list_install"); ?>');
						$(self).parents('.widget').addClass('notinstalled').removeClass('installed');
						$('#messageDialog').html(sprintf('<?php echo addslashes($this->translator('widget_list_uninstall_success')); ?>', arr[1], arr[0]))
							.dialog({
								title: '<?php echo addslashes($this->translator('common_dialog_message')); ?>',
								dialogClass: 't_a_ui_dialog',
								modal: true,
						    	show: { effect: 'fade' },
								open: function(event, ui) {
									setTimeout(function() {
										$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
									}, 3000);
								}
							});
					}
				});
				<?php endif; ?>
				break;
		}
	});
});
//]]>
</script>
