<?php 
/**
 * AmanCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@amancms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2010-2012 KhanSoft Limited (http://www.khansoft.com)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: list.phtml 4185 2010-08-01 16:31:02Z mehrab $
 * @since		1.0.0
 */
?>
<?php
$this->headTitle($this->translator('language_list_page_title'));
?>




<!-- Upload new package -->
<?php if ($this->allow('upload')) : ?>

<div class="box grid_5 alpha">	
	<h2 class="box_head"><?php echo $this->translator('language_list_upload_head'); ?></h2>
	<div class="block">
		<form method="post" action="<?php echo $this->url(array(), 'core_language_upload'); ?>" enctype="multipart/form-data">
			<fieldset>
				<span><?php echo $this->translator('language_list_upload_desc'); ?></span>
				<div><input type="file" name="file" style="width: 180px" /></div>
			</fieldset>
			<div class="button_bar clearfix"><button type="submit"><span><?php echo $this->translator('language_list_upload_button'); ?></span></button></div>
		</form>
	</div>		
</div>

<?php endif; ?>

<!-- Add new language -->

<?php if ($this->allow('new')) : ?>
<div class="box grid_11 omega">
	<h2 class="box_head"><?php echo $this->translator('language_list_create_new'); ?></h2>
	<div class="block">
		<form method="post" id="addLanguageForm" action="<?php echo $this->url(array(), 'core_language_new'); ?>">
			<fieldset class="label_side">
				<label for="">
				<span><?php echo $this->translator('language_list_select_module'); ?>:</span>
				</label>
				
				<div>
					<select name="module_name" id="moduleSelect">
						<option value="">---</option>
						<?php foreach ($this->modules as $module) : ?>
						<option value="<?php echo $module; ?>"><?php echo $module; ?></option>
						<?php endforeach; ?>
					</select>
					<div class="required_tag"></div>
				</div>
			</fieldset>
			<fieldset class="label_side">
				<label for=""><span><?php echo $this->translator('language_list_select_widget'); ?>:</span></label>
				<div class="clearfix">
					<select name="widget" id="widgetSelect" >
						<option value="">---</option>
					</select>
				</div>
			</fieldset>
			<fieldset class="label_side">
				<label for=""><span><?php echo $this->translator('language_list_new_language_code'); ?>:</span></label>
				<div class="clearfix">
					<input type="text" style="width: 100px" class="text" name="language" id="language" />
					<div class="required_tag"></div>
				</div>
			</fieldset>
			<div class="button_bar clearfix">
				<label>&nbsp;</label>
				<button type="submit"><span><?php echo $this->translator('language_list_new_language_button'); ?></span></button>
			</div>			
		</form>
	</div>
</div>			
<?php endif; ?>
<div class="clear"></div>
<div class="flat_area clearfix">
	<h2><?php echo $this->translator('language_list_breadcrumb'); ?><small> - <?php echo $this->translator('language_list_guide'); ?></small></h2>
	
</div>
<!-- Left column -->
<div class="box grid_3 alpha">
	<!-- Modules -->
	<div class="block">
		<ul class="flat" id="moduleFilter">
			<?php foreach ($this->modules as $index => $module) : ?>
			<li<?php if (0 == $index) : ?> class="shade"<?php endif; ?>><a href="javascript: void(0);"><?php echo $module; ?></a></li>
			<?php endforeach; ?>
		</ul>
	</div>		
</div>

<!-- Right column -->
<div class="box grid_13 omega no_title">
	<div class="block">	
		<div class="section">		
			<!-- List of widgets group by module -->
			<?php foreach ($this->modules as $moduleIndex => $module) : ?>
			<div id="<?php echo $module; ?>Module" class="widgetsModule" style="display: none">
				<?php if ($langs = $this->langLoader($module)) : ?>
				<div class="t_a_bottom">
					<?php if ($langs['module']) : ?>
					<strong><?php echo $this->translator('language_list_available'); ?>:</strong><br />
				
					<?php foreach ($langs['module'] as $index => $lang) : ?>
					<?php if ($index > 0) : ?>, <?php endif; ?>
				
					<?php if ($this->allow('edit')) : ?>
					<a href="<?php echo $this->url(array('module_name' => $module, 'language' => $lang), 'core_language_edit_module'); ?>"><?php echo $lang; ?></a>
					<?php else : ?>
						<?php echo $lang; ?>
					<?php endif; ?>
					<?php endforeach; ?>
				<?php else : ?>
					<?php echo $this->translator('language_list_have_not_any_language'); ?>
				<?php endif; ?>
					<hr />
				</div>
			
			<?php if (count($langs['widget']) > 0) : ?>
			<div class="block ">
				<div class="columns shade clearfix">
					<div class="col_33">
						<div class="section"><strong><?php echo $this->translator('language_list_widgets'); ?></strong></div>
					</div>
					<div class="col_66">
						<div class="section"><strong><?php echo $this->translator('language_list_available'); ?></strong></div>
					</div>				
				</div>	 
			
				<!-- List widget languages -->
			
				<?php foreach ($langs['widget'] as $widget => $langs) : ?>
				
					<div class="columns clearfix">
						<div class="col_33">
							<div class="section"><?php echo $widget; ?></div>
						</div>
						
						<div class="col_66">
							<div class="section">
								<?php if (count($langs) == 0) : ?>
								<?php echo $this->translator('language_list_widget_have_not_any_language'); ?>
								<?php else : ?>
								<?php foreach ($langs as $index => $lang) : ?>
								<?php if ($index > 0) : ?>, <?php endif; ?>
								
								<?php if ($this->allow('edit')) : ?>
								<a href="<?php echo $this->url(array('module_name' => $module, 'widget' => $widget, 'language' => $lang), 'core_language_edit_widget'); ?>"><?php echo $lang; ?></a>
								<?php endif; ?>
								<?php endforeach; ?>
								<?php endif; ?>
							</div>
						</div>
					</div>
				<?php endforeach; ?>
			</div>
			<?php endif; ?>
		<?php endif; ?>
		</div>	
		<?php endforeach; ?>
		<br />
		
	</div>
</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
	/**
	 * Data list hover handler
	 */
	$('.t_a_ui_data_list_content').hover(function() {
		$(this).find('.t_a_ui_helper_action').show();
	}, function() {
		$(this).find('.t_a_ui_helper_action').hide();
	});

	/**
	 * Show all the widgets belonging to first module
	 */
	$('.widgetsModule:first').show();

	/**
	 * Filter widget by module
	 */
	$('#moduleFilter').find('a').click(function() {
		$('.widgetsModule').hide();
		$('#' + $(this).html() + 'Module').show();	

		$('#moduleFilter').find('li').removeClass('shade');
		$(this).parent().addClass('shade');
	});	

	/**
	 * Show all available widgets based on selected module
	 */
	var gWidgets = JSON.parse('<?php echo $this->widgets; ?>');
	$('#moduleSelect').bind('change', function() {
		$('#widgetSelect').html('').append($('<option/>').val('').html('---'));
		var module = $(this).val();
		for (var i in gWidgets[module]) {
			$('#widgetSelect').append($('<option/>').val(gWidgets[module][i]).html(gWidgets[module][i]));
		}
	});

	/**
	 * Validate form
	 */
	$('#addLanguageForm').validate({
		rules: {
			module_name: {required: true},
			language: {required: true}
	    },
	    messages: {
	    	module_name: {
	        	required: "<?php echo $this->translator('language_list_module_required'); ?>"
			},
			language: {
	        	required: "<?php echo $this->translator('language_list_language_required'); ?>"
			}
		}
	});
});
</script>
