<?php 
/**
 * AmanCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@amancms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2010-2012 KhanSoft Limited (http://www.khansoft.com)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: index.phtml 5286 2010-09-03 08:08:44Z mehrab $
 * @since		2.0.7
 */
?>
<?php 
$this->headTitle($this->translator('permalink_index_page_title'));

$this->headLink()->appendStylesheet($this->APP_STATIC_SERVER . '/js/jquery.autocomplete/jquery.autocomplete.css');

$this->headScript()
	->appendFile($this->APP_STATIC_SERVER . '/js/jquery.bgiframe/jquery.bgiframe.min.js')
	->appendFile($this->APP_STATIC_SERVER . '/js/jquery.autocomplete/jquery.autocomplete.js');
?>
<div class="flat_area grid_16 clearfix">
	<h2><?php echo $this->translator('permalink_index_breadcrumb'); ?></h2>	
</div>

<div class="grid_16"><?php echo $this->flashMessenger(); ?></div>

<form method="post" action="<?php echo $this->url(array(), 'core_permalink_index'); ?>" id="configForm">
<?php foreach ($this->permalinks as $name => $route) : ?>
<div class="box grid_16 no_title clearfix routeConfig" id="<?php echo $name; ?>_Route">
	<div class="block">
		<div class="section">
			<h2><?php echo $route['description']; ?></h2>
		</div>
		<hr />
		<div class="section"><?php echo $this->translator('permalink_index_params_guide'); ?>:</div>
		
		<!-- List of parameters -->
		<div class="prefix_1 suffix_1 section">
		<?php foreach ($route['params'] as $paramName => $settings) : ?>
			{<?php echo $settings['name']; ?>}<?php if ('true' == $settings['required']) : ?> *<?php endif; ?>,
		<?php endforeach; ?>
		</div>
		
		<div class="prefix_1 suffix_1">
			<!-- Default URL -->
			<div class="columns clearfix">
				<div class="col_25">
					<?php echo $this->translator('permalink_index_select_default_url'); ?>:
				</div>
				<div class="col_75">
					<input type="radio" name="urlType[<?php echo $name; ?>]" value="default"<?php if (!isset($this->usedPemalinks[$name]) || (isset($this->usedPemalinks[$name]) && $this->usedPemalinks[$name]['url'] == $route['default'])) : ?> checked="checked"<?php endif; ?> />
				
					<input name="url[<?php echo $name; ?>][]" type="text" style="width: 350px" readonly="readonly" disabled="disabled" value="<?php echo $route['default']; ?>" />
				</div>
			</div>
			
			<hr />
		
			<!-- List of pre-defined URLs -->
			<div class="columns clearfix">
				<div class="col_25">
					<?php echo $this->translator('permalink_index_select_predefined_url'); ?>:
				</div>
				<div class="col_75">
					<?php foreach ($route['predefined'] as $url) : ?>
					<input type="radio" name="urlType[<?php echo $name; ?>]" value="predefined"<?php if (isset($this->usedPemalinks[$name]) && $this->usedPemalinks[$name]['url'] == $url) : ?> checked="checked"<?php endif; ?> />
					<input name="url[<?php echo $name; ?>][]" type="text" style="width: 350px" value="<?php echo $url; ?>" readonly="readonly" disabled="disabled" />
					<br />
					<?php endforeach; ?>
				</div>				
			</div>
			
			<hr />
			
			<!-- Custom URL -->
			<div class="columns clearfix">
				<div class="col_25">
					<?php echo $this->translator('permalink_index_cutome_url'); ?>:
				</div>
				<div class="col_75">
					<input type="radio" name="urlType[<?php echo $name; ?>]" value="custom"<?php if (isset($this->usedPemalinks[$name]) && $this->usedPemalinks[$name]['type'] == 'custom') : ?> checked="checked"<?php endif; ?> />
					<input id="customUrl_<?php echo $name; ?>" name="url[<?php echo $name; ?>][]" type="text" style="width: 350px" 
						<?php if (isset($this->usedPemalinks[$name]) && $this->usedPemalinks[$name]['type'] == 'custom') : ?>
						value="<?php echo $this->usedPemalinks[$name]['url']; ?>"
						<?php else : ?>
						disabled="disabled"
						<?php endif; ?> />
				</div>
				
				<input type="hidden" name="routeNames[]" value="<?php echo $name; ?>" />
			</div>
		</div>
		<br />
	</div>
</div>
<?php endforeach; ?>

<div class="box grid_16 no_title clearfix">
	<div class="button_bar clearfix">
		<button type="submit"><span><?php echo $this->translator('permalink_index_save_button'); ?></span></button>
	</div>
</div>
</form>

<script type="text/javascript">
$(document).ready(function() {
	/**
	 * Disbable/enable text boxes
	 */
	$('#configForm').find('input[type="radio"]').change(function() {
		$(this).parents('.routeConfig').find('input[type="text"]').attr('disabled', 'disabled');
		$(this).parent().find('input[type="text"]').removeAttr('disabled');
	});

	/**
	 * Show available parameters based on user's input
	 */
	<?php foreach ($this->permalinks as $name => $route) : ?>
	$('#customUrl_<?php echo $name; ?>').autocomplete([<?php foreach (array_keys($route['params']) as $index => $paramName) : ?><?php if ($index > 0) : ?>,<?php endif; ?>'{<?php echo $paramName; ?>}'<?php endforeach; ?>], {
		multiple: true,
		multipleSeparator: ''
	}); 
	<?php endforeach; ?>
});
</script>

