<?php 
/**
 * AmanCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@amancms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2010-2012 KhanSoft Limited (http://www.khansoft.com)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: login.phtml 4185 2010-08-01 16:31:02Z mehrab $
 * @since		1.0.0
 */
?>
<?php 
$this->headTitle($this->translator('auth_login_page_title'));
$this->headScript()->appendFile($this->APP_STATIC_SERVER . '/js/jquery.validate/jquery.validate.min.js');
?>


<div class="isolate" style="height: 335px">
	<div id="login_box" class="center">
		<div class="main_container clearfix ui-sortable">
			<div class="box no_titlebar" style="opacity: 1;">
				<div class="block" style="opacity: 1;">
					<?php if($this->flashMessenger() != ""):?>
					<div class="section">
						<div class="alert dismissible alert_red">
							<img width="24" height="24" src="<?php echo $this->APP_STATIC_SERVER . '/skins/'. $this->APP_TEMPLATE . '/' . $this->APP_SKIN;?>/images/icons/small/grey/locked.png" />
							<span><?php echo $this->flashMessenger(); ?></span>
						</div>
					</div>
					<?php endif;?>
					<div class="section">
						<div class="alert dismissible alert_light">
							<img width="24" height="24" src="<?php echo $this->APP_STATIC_SERVER . '/skins/'. $this->APP_TEMPLATE . '/' . $this->APP_SKIN;?>/images/icons/small/grey/locked.png">
							<strong>Welcome to Startex Marketing Services.</strong> Please enter your details to login.
						</div>
					</div>	
					<form id="loginForm" class="validate_form" action="<?php echo $this->url(array(), 'core_auth_login'); ?>" method="post" >
						<fieldset class="label_side">
							<label for="username_field"><?php echo $this->translator('auth_login_user_name'); ?></label>
							<div>
								<input type="text" class="required text error" id="username" name="username">
							</div>
						</fieldset>						
						<fieldset class="label_side">
							<label for="password_field"><?php echo $this->translator('auth_login_password'); ?></label>
							<div>
								<input type="password" class="required text error" id="password" name="password">							
							</div>
						</fieldset>					
						<div class="button_bar clearfix">
							<a href="<?php echo $this->url(array(), 'core_auth_forgot'); ?>" style="color: blue;"><span><?php echo $this->translator('auth_forgot_password'); ?></span></a>
							<!--<button id="btnForgotPassword" class="blue send_right" type="button" value="<?php echo $this->url(array(), 'core_auth_forgot'); ?>">
								<span><?php echo $this->translator('auth_forgot_password'); ?></span>
							</button>  -->
							<button class="blue send_right" type="submit">
								<span><?php echo $this->translator('auth_login_submit_button'); ?></span>
							</button>
						</div>					
					</form>	
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function() {
	$('#btnForgotPassword').click(function(){
		window.location = $(this).val();
	});
	/**
	 * Validate form
	 */
	$('#loginForm').validate({
		rules: {
			username: {
		  		required: true, email: true
			},
			password: {
				required: true
			}
	    },
	    messages: {
	    	username: {
	        	required: "<?php echo $this->translator('auth_login_user_name_required'); ?>",
	        	email: "<?php echo $this->translator('auth_login_user_name_email');?>"
			},
			password: {
	        	required: "<?php echo $this->translator('auth_login_password_required'); ?>"
			}
		}
	});
});
</script>
