<?php 
/**
 * AmanCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@amancms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2010-2012 KhanSoft Limited (http://www.khansoft.com)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: add.phtml 4185 2010-08-01 16:31:02Z mehrab $
 * @since		1.0.0
 */
?>
<?php 
$this->headTitle($this->translator('user_add_page_title'));
$this->headScript()->appendFile($this->APP_STATIC_SERVER . '/js/jquery.validate/jquery.validate.min.js');
?>

<div class="box grid_10 no_titlebar">
	<div class="block">
		<h2 class="section"><?php echo $this->translator('user_add_breadcrumb'); ?></h2>
<!--  		<a class="btn ui-state-default ui-corner-all clearfix" href="<?php echo $this->url(array(), 'core_user_list'); ?>">
			<span class="ui-icon ui-icon-person" style="padding: 0px"></span>
			<?php echo $this->translator('user_list_breadcrumb'); ?>
		</a> -->
		<span class="section"><?php echo $this->translator('user_add_guide'); ?></span>
		
		<?php if($this->SUCCESS):?>   		
    	<div class="section">
		   	<div class="alert dismissible alert_green">
				<img width="24" height="24" src="<?php echo $this->APP_STATIC_SERVER."/skins/".$this->APP_TEMPLATE."/".$this->APP_SKIN;?>/images/icons/small/white/alert.png">
				<?php echo $this->SUCCESS;?>
			</div>
		</div>
		<?php endif;?>	
		<form class="forms" method="post" action="<?php echo $this->url(array(), 'core_user_add'); ?>" id="form1">
			<fieldset class="label_side">
				<label><span><?php echo $this->translator('user_firstname'); ?>:</span></label>
				<div>					
					<input type="text" id="firstname" name="firstname"  />
					<div class="required_tag tooltip hover left"></div>
				</div>
			</fieldset>
			<fieldset class="label_side">
				<label><span><?php echo $this->translator('user_lastname'); ?>:</span></label>
				<div>					
					<input type="text" id="lastname" name="lastname"  />
					<div class="required_tag tooltip hover left"></div>
				</div>
			</fieldset>			
			<fieldset class="label_side">
				<label><span><?php echo $this->translator('user_email'); ?>:</span></label>
				<div>					
					<input type="text" id="email" name="email" />
					<div class="required_tag tooltip hover left"></div>
				</div>
			</fieldset>
			<fieldset class="label_side">
				<label><span><?php echo $this->translator('user_password'); ?>:</span></label>
				<div>					
					<input type="password" id="password" name="password"  />
					<div class="required_tag tooltip hover left"></div>
				</div>
			</fieldset>
			<fieldset class="label_side">
				<label><span><?php echo $this->translator('user_confirm_password'); ?>:</span></label>
				<div>					
					<input type="password" id="confirmPassword" name="confirmPassword" />
					<div class="required_tag tooltip hover left"></div>
				</div>
			</fieldset>
			
			<fieldset class="label_side">
				<label><span><?php echo $this->translator('user_offic_phone'); ?>:</span></label>
				<div>					
					<input type="password" id="offic" name="office" />
				</div>
			</fieldset>
			<fieldset class="label_side">
				<label><span><?php echo $this->translator('user_home_phone'); ?>:</span></label>
				<div>					
					<input type="password" id="home" name="home" />
				</div>
			</fieldset>
			<fieldset class="label_side">
				<label><span><?php echo $this->translator('user_mobil_phone'); ?>:</span></label>
				<div>					
					<input type="password" id="mobile" name="mobile" />
				</div>
			</fieldset>
			<fieldset class="label_side">
				<label><span><?php echo $this->translator('user_address'); ?>:</span></label>
				<div>					
					<input type="password" id="address" name="address" />
				</div>
			</fieldset>
			<fieldset class="label_side">
				<label><span><?php echo $this->translator('user_customer'); ?>:</span></label>
				<div>					
					<select id="customer" name="customer" >
						<option>-----</option>
					</select>
					<div class="required_tag tooltip hover left"></div>
				</div>
			</fieldset>
			<fieldset class="label_side">
				<label><span><?php echo $this->translator('user_lang'); ?>:</span></label>
				<div>					
					<select id="language" name="language" >
						<option>-----</option>
					</select>
					<div class="required_tag tooltip hover left"></div>
				</div>
			</fieldset>		
			<fieldset class="label_side">
				<label><span><?php echo $this->translator('user_role'); ?>:</span></label>		
				<div>					
					<select name="role" id="role" class="">
						<option value="">---</option>
						<?php foreach ($this->roles as $role) : ?>
						<option value="<?php echo $role->role_id; ?>"><?php echo $role->description; ?></option>
						<?php endforeach; ?>
					</select>
				</div>
			</fieldset>
			<div class="button_bar clearfix">					
				<?php echo $this->tokenElement; ?>				
				<button type="submit">
					<img alt="" src="<?php echo $this->APP_STATIC_SERVER."/skins/".$this->APP_TEMPLATE."/".$this->APP_SKIN."/images/icons/small/white/bended_arrow_right.png";?>" width="24" height="24" />
					<span><?php echo $this->translator('user_add_save_button'); ?></span>				
				</button>
			</div>
			
		</form>		
	</div>
</div>


<!-- Side Bar -->
<div id="sidebar">
	<div class="sidebar-content">
		<a id="close_sidebar" class="btn ui-state-default full-link ui-corner-all" href="#drill">
					<span class="ui-icon ui-icon-circle-arrow-e"></span>
					Close Sidebar
				</a>
		<a id="open_sidebar" class="btn tooltip ui-state-default full-link icon-only ui-corner-all" title="Open Sidebar" href="#"><span class="ui-icon ui-icon-circle-arrow-w"></span></a>
		<div class="hide_sidebar">
			<div class="portlet ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
				<div class="portlet-header ui-widget-header">
					<?php echo $this->translator('menu_system_user', 'core'); ?>
				</div>
				<div class="portlet-content">
					<ul class="side-menu">					                
		                <?php if ($this->routeAccessor('core_role_list')) : ?>
						<li><a href="<?php echo $this->url(array(), 'core_role_list'); ?>"><?php echo $this->translator('menu_role', 'core'); ?></a></li>
						<?php endif; ?>
						
		                <?php if ($this->routeAccessor('core_user_list')) : ?>
						<li><a href="<?php echo $this->url(array(), 'core_user_list'); ?>"><?php echo $this->translator('menu_user', 'core'); ?></a></li>
						<?php endif; ?>
						
						<?php if ($this->routeAccessor('core_privilege_list')) : ?>
						<li><a href="<?php echo $this->url(array(), 'core_privilege_list'); ?>"><?php echo $this->translator('menu_privilege', 'core'); ?></a></li>
						<?php endif; ?>
					</ul>
				</div>
			</div>
		</div>
	</div>
	
</div>
<!-- End Side Bar -->
<div class="clear"></div>
<script type="text/javascript">
//<![CDATA[
$(document).ready(function() {
	/**
	 * Validate form
	 */
	$('#form1').validate({
		rules: {
			full_name: {
				required: true
			},
			username: {
		  		required: true,
		  		minlength: 5,
		  		maxlength: 255,
		  		remote: '<?php echo $this->url(array('check_type' => 'username'), 'core_user_check'); ?>'
			},
			email: {
				required: true,
				email: true,
				remote: '<?php echo $this->url(array('check_type' => 'email'), 'core_user_check'); ?>'
			},
			password: {
		  		required: true,
		  		minlength: 5
			},
			confirmPassword: {
				equalTo: '#password'
			},
			role: {
				required: true
			}
	    },
	    messages: {
	    	full_name: {
	        	required: "<?php echo $this->translator('user_full_name_required'); ?>"
	    	},
	    	username: {
	        	required: "<?php echo $this->translator('user_user_name_required'); ?>",
				minlength: "<?php echo $this->translator('user_user_name_minlength'); ?>",
				maxlength: "<?php echo $this->translator('user_user_name_maxlength'); ?>",
				remote: "<?php echo $this->translator('user_user_name_exist'); ?>"
			},
			email: { 
	        	required: "<?php echo $this->translator('user_email_required'); ?>",
	        	email: "<?php echo $this->translator('user_email_invalid'); ?>",
		        remote: "<?php echo $this->translator('user_email_exist'); ?>"
	    	},
	    	password: {
				required: "<?php echo $this->translator('user_password_required'); ?>",
				minlength: "<?php echo $this->translator('user_password_minlength'); ?>"				
			},
			confirmPassword: {
				equalTo: "<?php echo $this->translator('user_confirm_password_error'); ?>"
			},
			role: {
				required: "<?php echo $this->translator('user_role_required'); ?>"
			}
		}
	});
});
//]]>
</script>
