<?php 
/**
 * AmanCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@amancms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2010-2012 KhanSoft Limited (http://www.khansoft.com)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: changepass.phtml 4185 2010-08-01 16:31:02Z mehrab $
 * @since		1.0.0
 */
?>
<?php 
$this->headTitle($this->translator('user_changepass_page_title'));
?>

<div class="flat_area grid_16 clearfix">
	<h2><?php echo $this->translator('user_changepass_breadcrumb'); ?></h2>	
</div>
<div class="grid_4"></div>
<div class="box grid_8 no_title">	
	<div class="block">
		<?php if(($message = $this->flashMessenger())!=""):?>
		<div class="response-msg success ui-corner-all"><span> &nbsp; </span> <?php echo $message; ?></div>
		<?php endif;?>

		<form class="forms" method="post" action="<?php echo $this->url(array(), 'core_user_changepass'); ?>" id="changepassForm">
			<fieldset class="top">
				<label for="">
					<?php echo $this->translator('user_changepass_new_password'); ?>:
					<span><?php echo $this->translator('user_password_guide'); ?></span></label>
				<div class="clearfix">
					<input type="password" class="field text small" name="password" id="password" />
					
					<div class="required_tag"></div>
				</div>
			</fieldset>
			<fieldset>
				<label for="">
					<?php echo $this->translator('user_changepass_confirm_password'); ?>:
					<span><?php echo $this->translator('user_confirm_password_guide'); ?></span>
				</label>
				<div class="clearfix">
					<input type="password" class="field text small" name="confirmPassword" id="confirmPassword" />
					<div class="required_tag"></div>
				</div>
			</fieldset>
			<div class="button_bar clearfix">			
				<?php echo $this->tokenElement; ?>
				<button type="submit" class="ui-button ui-state-default ui-corner-all"><span><?php echo $this->translator('user_changepass_save_button'); ?></span></button>
			</div>			
		</form>
	</div>
</div>

<div class="clear"></div>

<script type="text/javascript">
//<![CDATA[
$(document).ready(function() {
	/**
	 * Validate form
	 */
	$('#changepassForm').validate({
		rules: {
			password: {
				required: true,
		  		minlength: 5
			},
			confirmPassword: {
				equalTo: '#password'
			}
	    },
	    messages: {
	    	password: {
	    		required: "<?php echo $this->translator('user_password_required'); ?>",
				minlength: "<?php echo $this->translator('user_password_minlength'); ?>"
			},
			confirmPassword: {
				equalTo: "<?php echo $this->translator('user_confirm_password_error'); ?>"
			}
		}
	});
});
//]]>
</script>
