<?php 
/**
 * AmanCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@amancms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2010-2012 KhanSoft Limited (http://www.khansoft.com)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: edit.phtml 4185 2010-08-01 16:31:02Z mehrab $
 * @since		1.0.0
 */
?>
<?php 
$this->headTitle($this->translator('user_edit_page_title'));
$this->headScript()->appendFile($this->APP_STATIC_SERVER . '/js/jquery.validate/jquery.validate.min.js');
?>

<div class="inner-page-title">
	<h3 class="float-left"><?php echo $this->translator('user_edit_breadcrumb'); ?></h3>	
	<div class="float-right">
		<a class="btn ui-state-default ui-corner-all clearfix" href="<?php echo $this->url(array(), 'core_user_list'); ?>">
			<span class="ui-icon ui-icon-person" style="padding: 0px"></span>
			<?php echo $this->translator('user_list_breadcrumb'); ?>
		</a>
	</div>
	<div class="clear"></div>
</div>


<div class="content-box content-box-header ui-corner-all">
	
	<div class="content-box-wrapper">
		<h4><?php echo $this->translator('user_edit_guide'); ?></h4>
		
		<?php if($this->flashMessenger()!=""):?>
		<div class="response-msg success ui-corner-all"><span> &nbsp; </span> <?php echo $this->flashMessenger(); ?></div>
		<?php endif;?>

		<form class="forms" method="post" action="<?php echo $this->url(array('user_id' => $this->user->user_id), 'core_user_edit'); ?>" id="editUserForm">
			<ul>
				<li>
					<label class="desc"><?php echo $this->translator('user_full_name'); ?>:</label>
					<div>						
						<input type="text" class="field text small"  name="full_name" id="full_name" value="<?php if (null != $this->user && null != $this->user->full_name) : ?><?php echo $this->user->full_name; ?><?php endif; ?>" />
					</div>
				</li>
				<li>
					<label class="desc"><?php echo $this->translator('user_user_name'); ?>:</label>										
					<div>						
						<input type="text" class="field text small" name="username" id="username" value="<?php if (null != $this->user && null != $this->user->user_name) : ?><?php echo $this->user->user_name; ?><?php endif; ?>" />
					</div>
				</li>
				<li>					
					<label class="desc"><?php echo $this->translator('user_password'); ?>:</label>
					<div>
						<input type="password" class="field text small"  name="password" id="password" />
					</div>
				</li>
				<li>
					<label class="desc"><?php echo $this->translator('user_confirm_password'); ?>:</label>					
					<div>
						<input type="password" class="field text small" name="confirmPassword" id="confirmPassword" />
					</div>
				</li>
				<li>
					<label class="desc"><?php echo $this->translator('user_email'); ?>:</label>
					<div>						
						<input type="text" class="field text small" name="email" id="email" value="<?php if (null != $this->user && null != $this->user->email) : ?><?php echo $this->user->email; ?><?php endif; ?>" />
					</div>
				</li>
				<li>
					<label class="desc"><?php echo $this->translator('user_role'); ?>:</label>					
					<div>						
						<select name="role" class="field select small" >
							<?php foreach ($this->roles as $role) : ?>
							<option value="<?php echo $role->role_id; ?>" <?php if ($this->user != null && $this->user->role_id == $role->role_id) : ?> selected<?php endif; ?>><?php echo $role->description; ?></option>
							<?php endforeach; ?>
						</select>
					</div>
				</li>
				<li>
					<label>&nbsp;</label>	
					<div>						
						<button type="submit" class="ui-button ui-state-default ui-corner-all"><span><?php echo $this->translator('user_edit_save_button'); ?></span></button>
					</div>
				</li>
			</ul>
		</form>
	</div>
</div>

<!-- Side Bar -->
<div id="sidebar">
	<div class="sidebar-content">
		<a id="close_sidebar" class="btn ui-state-default full-link ui-corner-all" href="#drill">
					<span class="ui-icon ui-icon-circle-arrow-e"></span>
					Close Sidebar
				</a>
		<a id="open_sidebar" class="btn tooltip ui-state-default full-link icon-only ui-corner-all" title="Open Sidebar" href="#"><span class="ui-icon ui-icon-circle-arrow-w"></span></a>
		<div class="hide_sidebar">
			<div class="portlet ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
				<div class="portlet-header ui-widget-header">
					<?php echo $this->translator('menu_system_user', 'core'); ?>
				</div>
				<div class="portlet-content">
					<ul class="side-menu">					                
		                <?php if ($this->routeAccessor('core_role_list')) : ?>
						<li><a href="<?php echo $this->url(array(), 'core_role_list'); ?>"><?php echo $this->translator('menu_role', 'core'); ?></a></li>
						<?php endif; ?>
						
		                <?php if ($this->routeAccessor('core_user_list')) : ?>
						<li><a href="<?php echo $this->url(array(), 'core_user_list'); ?>"><?php echo $this->translator('menu_user', 'core'); ?></a></li>
						<?php endif; ?>
						
						<?php if ($this->routeAccessor('core_privilege_list')) : ?>
						<li><a href="<?php echo $this->url(array(), 'core_privilege_list'); ?>"><?php echo $this->translator('menu_privilege', 'core'); ?></a></li>
						<?php endif; ?>
					</ul>
				</div>
			</div>
		</div>
	</div>
	
</div>
<!-- End Side Bar -->
<div class="clear"></div>

<script type="text/javascript">
//<![CDATA[
$(document).ready(function() {
	/**
	 * Validate form
	 */
	$('#editUserForm').validate({
		rules: {
		    full_name: {
				required: true
			},
			username: {
		  		required: true,
		  		minlength: 5,
		  		maxlength: 255,
		  		remote: '<?php echo $this->url(array('check_type' => 'username'), 'core_user_check'); ?>?original=<?php echo $this->user->user_name; ?>'
			},
			email: {
				required: true,
				email: true,
				remote: '<?php echo $this->url(array('check_type' => 'email'), 'core_user_check'); ?>?original=<?php echo $this->user->email; ?>'
			},
			password: {
		  		minlength: 5
			},
			confirmPassword: {
				equalTo: '#password'
			},
			role: {
				required: true
			}
	    },
	    messages: {
	    	full_name: {
	        	required: "<?php echo $this->translator('user_full_name_required'); ?>"
	    	},
	    	username: {
	        	required: "<?php echo $this->translator('user_user_name_required'); ?>",
				minlength: "<?php echo $this->translator('user_user_name_minlength'); ?>",
				maxlength: "<?php echo $this->translator('user_user_name_maxlength'); ?>",
				remote: "<?php echo $this->translator('user_user_name_exist'); ?>"
			},
			email: { 
				required: "<?php echo $this->translator('user_email_required'); ?>",
	        	email: "<?php echo $this->translator('user_email_invalid'); ?>",
		        remote: "<?php echo $this->translator('user_email_exist'); ?>"
	    	},
	    	password: {
	    		minlength: "<?php echo $this->translator('user_password_minlength'); ?>"
			},
			confirmPassword: {
				equalTo: "<?php echo $this->translator('user_confirm_password_error'); ?>"
			},
			role: {
				required: "<?php echo $this->translator('user_role_required'); ?>"
			}
		}
	});
});
//]]>
</script>
