<?php 
/**
 * AmanCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@amancms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2010-2012 KhanSoft Limited (http://www.khansoft.com)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: role.phtml 4536 2010-08-12 09:53:07Z mehrab $
 * @since		1.0.0
 */
?>
<?php $this->headTitle($this->translator('rule_role_page_title'));?>

<div class="flat_area grid_16 clearfix">
	<h2><?php echo $this->translator('rule_role_title'); ?></h2>	
</div>

<?php if ($this->role->locked) : ?>
<div class="flat_area grid_16 clearfix">
	<?php echo $this->translator('rule_role_role_desc'); ?>: <b><?php echo $this->role->name; ?> - <?php echo $this->role->description; ?></b><br />
	<?php echo $this->translator('rule_role_role_locked'); ?>
</div>
<?php else : ?>
<form id="form1" class="forms" method="post" action="<?php echo $this->url(array('role_id' => $this->role->role_id), 'core_rule_set_role'); ?>">
<div class="box grid_16 round_all clearfix">
	<h2 class="box_head">
		<?php echo $this->translator('rule_role_role_desc'); ?>: <b><?php echo $this->role->name; ?> - <?php echo $this->role->description; ?></b>			
	</h2>
	<div class="controls">
		<select name="" id="moduleFilter" class="uniform">
            <?php foreach ($this->modules as $module):?>
            <option value="<?php echo $module;?>"><?php echo $module;?></option>
            <?php endforeach;?>
        
        </select>
	</div>
	
	<div class="block">		
		<div class="section">
			<div><h3><?php echo $this->translator('rule_role_guide'); ?></h3></div>							
			<!-- List of resources -->
			<?php foreach ($this->modules as $index => $module) : ?>
			<div id="<?php echo $module; ?>Resource" class="moduleResource" style="display: <?php echo (($index == 0) ? 'block' : 'none'); ?>">
				<?php if (($resources = $this->ruleLoader()->getResources($module))== true) : ?>
				<?php foreach ($resources as $i => $resource) : ?>
				<div class="grid_5 box">
						<!-- Resource description -->
						<h2 class="box_head "><?php echo $resource->description; ?></h2>
						<div class="block">
							<div class="button_bar clearfix">
							<!-- Resource privileges -->
								<a class="btn ui-state-default selectAllAction" href="javascript: void(0);"><?php echo $this->translator('rule_role_select_all'); ?></a>
								<a class="btn ui-state-default deselectAllAction" href="javascript: void(0);"><?php echo $this->translator('rule_role_deselect_all'); ?></a>
								
							</div>						
							<ul class="flat">
							<?php foreach ($privileges = $this->ruleLoader()->getByRole($resource, $this->role->role_id) as $index => $priv) : ?>
								<li><input type="checkbox" name="privileges[]" value="<?php echo $priv->privilege_id; ?>_<?php echo $resource->module_name; ?>:<?php echo $resource->controller_name; ?>"<?php if ($priv->allow == null || $priv->allow == 0) : ?> <?php else : ?> checked="checked"<?php endif; ?> /> <?php echo $priv->description; ?></li>
								<?php endforeach; ?>
							</ul>
						</div>
					</div>
					<?php endforeach; ?>					
					<?php endif; ?>
					<div class="clearfix"></div>
				</div>
				<?php endforeach; ?>
			
		</div>
		<div class="button_bar clearfix">			
			<button class="send_right" type="submit" id="saveRoles"><span><?php echo $this->translator('rule_role_submit_button'); ?></span></button>
		</div>
	</div>
</div>
</form>

<div class="clear"></div>
<script type="text/javascript">
//<![CDATA[
$(document).ready(function() {
	$('#saveRoles').click(function(){
		$('#form1').submit();
	});
	/**
	 * Load resource based on selected module
	 */
	$('#moduleFilter').change(function() {
		$('.moduleResource').hide();
		$('#' + $(this).val() + 'Resource').show();
	});

	/**
	 * Select all handler
	 */
	$('a.selectAllAction').click(function() {
		$(this).parent().parent().find('input[type="checkbox"]').each(function() {
			$(this).attr('checked', 'checked');
		});
	});

	/**
	 * Deselect all handler
	 */
	$('a.deselectAllAction').click(function() {
		$(this).parent().parent().find('input[type="checkbox"]').each(function() {
			$(this).removeAttr('checked');
		});
	});
});
//]]>
</script>
<?php endif; ?>
