<?php 
/**
 * AmanCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@amancms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2010-2012 KhanSoft Limited (http://www.khansoft.com)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: user.phtml 4537 2010-08-12 09:53:42Z mehrab $
 * @since		1.0.0
 */
?>
<?php 
$this->headTitle($this->translator('rule_user_page_title'));
?>

<div class="flat_area  grid_16 clearfix">
	<h2>
		<?php echo $this->translator('rule_user_breadcrumb'); ?> 
		<div class="holder"><a href="<?php echo $this->url(array(), 'core_user_list'); ?>"><?php echo $this->translator('user_list_breadcrumb'); ?></a></div>
	
	</h2>
	<p> <?php echo $this->translator('rule_user_desc'); ?> <a href=""> <?php echo $this->user->name; ?></a> </p>
</div>

<?php if (!$this->user->is_active) : ?>
<div class="box grid_16 no_title clearfix">
	<div class="block">
		<div class="section">
			<h2><?php echo $this->translator('rule_user_desc'); ?><small> - <?php echo $this->user->user_name; ?> - <?php echo $this->user->full_name; ?></small></h2>
			<p>
				<?php echo $this->translator('rule_user_is_not_actived'); ?>
			</p>
		</div>
	</div>

	
</div>
<?php else : ?>
<form method="post" action="<?php echo $this->url(array('user_id' => $this->user->user_id), 'core_rule_set_user'); ?>">

<div class="box grid_16 clearfix">
	<div class="indented_button_bar clearfix">
		<button type="submit" class="dark blue text_only has_text send_right">
			<span><?php echo $this->translator('rule_user_submit_button'); ?></span>
		</button>
		<p>
			<?php echo $this->translator('rule_user_guide'); ?>
		</p>
	</div>
</div>

<div class="box grid_5 alpha">
	<!-- List of modules -->
	<div class="block">
		<ul id="modules" class="flat">
			<?php foreach ($this->modules as $index => $module) : ?>
			<li<?php if ($index == 0) : ?> class="shade"<?php endif; ?>><a href="javascript: void(0);"><?php echo $module; ?></a></li>
			<?php endforeach; ?>
		</ul>
	</div>
</div>
<div class="box grid_11 no_title omega">
	<!-- List of resources -->
	<div class="block">
		<div class="section">
			<?php foreach ($this->modules as $index => $module) : ?>
			<div id="<?php echo $module; ?>Resource" class="moduleResource" style="display: <?php echo (($index == 0) ? 'block' : 'none'); ?>">
				<?php if ($resources = $this->ruleLoader()->getResources($module)) : ?>
				<?php foreach ($resources as $i => $resource) : ?>
				<div class="box grid_16 clearfix">
					<!-- Resource description -->				
					<h2 class="box_head"><?php echo $resource->description; ?></h2>
					<div class="controls"><a href="javscript:void(0);"></a></div>				
					<!-- Resource privileges -->
					<div class="block">					
						<ul class="flat">
							<li><a class="selectAllAction" href="javascript: void(0);"><?php echo $this->translator('rule_role_select_all'); ?></a> &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp; <a class="deselectAllAction" href="javascript: void(0);"><?php echo $this->translator('rule_role_deselect_all'); ?></a></li>
							<?php foreach ($privileges = $this->ruleLoader()->getByUser($resource, $this->user->user_id) as $index => $priv) : ?>
							<li><input type="checkbox" name="privileges[]" value="<?php echo $priv->privilege_id; ?>_<?php echo $resource->module_name; ?>:<?php echo $resource->controller_name; ?>"<?php if ($priv->allow == null || $priv->allow == 0) : ?> <?php else : ?> checked="checked"<?php endif; ?> /> <?php echo $priv->description; ?></li>
							<?php endforeach; ?>
						</ul>
					</div>
				</div>
				<?php endforeach; ?>
				
				<?php endif; ?>
			</div>
			<?php endforeach; ?>
		</div>
	</div>	
</div>
</form>

<script type="text/javascript">
$(document).ready(function() {
	/**
	 * Load resource based on selected module
	 */
	//$('.moduleResource:first').show();
	$('#modules').find('li').first().addClass('shade');
	$('#modules').find('a').click(function() {
		$('.moduleResource').hide();
		$('#' + $(this).html() + 'Resource').show();

		$('#modules').find('li').removeClass('shade');
		$(this).parent().addClass('shade');
	});

	/**
	 * Select all handler
	 */
	$('a.selectAllAction').click(function() {
		$(this).parent().parent().find('input[type="checkbox"]').each(function() {
			$(this).attr('checked', 'checked');
		});
	});

	/**
	 * Deselect all handler
	 */
	$('a.deselectAllAction').click(function() {
		$(this).parent().parent().find('input[type="checkbox"]').each(function() {
			this.checked = false;
		});
	});
});
</script>
<?php endif; ?>
