<?php 
/**
 * AmanCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@amancms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2010-2012 KhanSoft Limited (http://www.khansoft.com)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: index.phtml 4185 2010-08-01 16:31:02Z mehrab $
 * @since		1.0.0
 */
?>
<?php
$this->headTitle($this->translator('dashboard_index_page_title'));

/**
 * Dashboard editor
 * @since 2.0.7
 */

?>

<div class="flat_area grid_16 clearfix">
	<h2>
		<?php echo $this->translator('dashboard_index_guide'); ?>
		<span class="holder">
			<p><small><a href="javascript: void(0);" class="t_a_ui_button_link" id="customizeButton"><span><?php echo $this->translator('dashboard_index_customize_button'); ?></span></a></small></p>
		</span>
	</h2>
</div>

<!-- Loading -->
<div id="loading" class="grid_12 t_a_bottom" style="display: none">&nbsp;</div>

<!-- Editor -->
<div class="grid_12 t_a_bottom t_a_ui_tabs" id="editor" style="display: none"></div>

<!-- Buttons for previewing/saving Dashboard layout -->
<div class="grid_12 t_a_bottom" id="layoutButtons" style="display: none">
	<h3><?php echo $this->translator('dashboard_index_layout'); ?></h3>
	<hr />
	
	<div class="t_a_textright">
		<button id="switchButton"><span><?php echo $this->translator('dashboard_index_preview_button'); ?></span></button>
		<button id="saveButton"><span><?php echo $this->translator('dashboard_index_save_button'); ?></span></button>
	</div>
</div>

<div id="dashboardLayout" style="width: 940px; margin: 0 auto; min-height: 150px; height: 150px"></div>

<div id="messageDialog"></div>

<script type="text/javascript">
var rootContainer = new Aman.Core.Layout.Container('dashboardLayout');
rootContainer.setBaseUrl('<?php echo $this->baseUrl(); ?>');
rootContainer.setBgColor('#1a1a1a');

$(document).ready(function() {
	$('#customizeButton').toggle(function() {
		$(this).find('span').html('<?php echo $this->escape($this->translator('dashboard_index_close_editor_button')); ?>');
		$('#loading').addClass('t_a_ui_helper_loading').show();
		
		$.ajax({
			url: '<?php echo $this->url(array(), 'core_dashboard_index'); ?>',
			type: 'POST',
			data: { act: 'edit' },
			success: function(response) {
				$('#editor').html(response).show();
				$('#loading').removeClass('t_a_ui_helper_loading').hide();
				$('#layoutButtons').show();

				rootContainer.toggleMode('CONFIG', false);
			}
		});
	}, function() {
		$(this).find('span').html('<?php echo $this->escape($this->translator('dashboard_index_customize_button')); ?>');
		$('#editor').hide();
		$('#layoutButtons').hide();
		rootContainer.toggleMode('PREVIEW', true);
	});

	/**
	 * Switch mode handler
	 */
	$('#switchButton').toggle(function() {
		$(this).find('span').html('<?php echo $this->escape($this->translator('dashboard_index_config_button')); ?>');
		rootContainer.toggleMode('PREVIEW', true);
	}, function() {
		$(this).find('span').html('<?php echo $this->escape($this->translator('dashboard_index_preview_button')); ?>');
		rootContainer.toggleMode('CONFIG', false);
	});

	/**
	 * Save layout handler
	 */
	$('#saveButton').click(function() {
		var layout = $.toJSON(rootContainer.save());
		
		$.ajaxq('dashboard', {
			url: '<?php echo $this->url(array(), 'core_dashboard_index'); ?>',
			type: 'POST',
			data: { act: 'save', layout: layout },
			success: function(response) {
				$('#messageDialog').html('<?php echo addslashes($this->translator('dashboard_index_save_success')); ?>')
					.dialog({
						title: '<?php echo addslashes($this->translator('common_dialog_message')); ?>',
						dialogClass: 't_a_ui_dialog',
						modal: true,
				    	show: { effect: 'fade' },
						open: function(event, ui) {
							setTimeout(function() {
								$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
							}, 3000);
						}
					});
			}
		});
	});

	/**
	 * Load the layout
	 */
	 Aman.Core.Layout.Lang.setLang({
		CONTAINER_COLS: 		  '<?php echo $this->escape($this->translator('page_layout_container_columns')); ?>',
		CONTAINER_REMOVE_CONFIRM: '<?php echo $this->escape($this->translator('page_layout_remove_container_confirm')); ?>',
		WIDGET_PREVIEW: 		  '<?php echo $this->escape($this->translator('page_layout_widget_preview')); ?>',
		WIDGET_BACK: 			  '<?php echo $this->escape($this->translator('page_layout_widget_back')); ?>',
		WIDGET_REMOVE_CONFIRM: 	  '<?php echo $this->escape($this->translator('page_layout_remove_widget_confirm')); ?>',
		WIDGET_CACHE: 			  '<?php echo $this->escape($this->translator('page_layout_widget_cache')); ?>',
		WIDGET_LOAD_AJAX:		  '<?php echo $this->escape($this->translator('page_layout_widget_load_ajax')); ?>',
		DEFAULT_OUTPUT:			  '<?php echo $this->escape($this->translator('page_layout_default_output')); ?>'
	});

	<?php if ($this->dashboardLayout) : ?>
	rootContainer.load(<?php echo $this->dashboardLayout; ?>, true);
	<?php endif; ?>
});
</script>
