<!-- Menu -->
			<div id="menu">
				<ul class="t_a_ui_mega_menu">
					<li><a href="<?php echo $this->url(array(), 'core_dashboard_index'); ?>"><?php echo $this->translator('menu_admin', 'core'); ?></a></li>
					
					<li>
						<a href="#"><?php echo $this->translator('menu_system', 'core'); ?></a>
						
						<div class="sub">
							<div class="row">
		                     	<ul>
									<li><span><?php echo $this->translator('menu_system_user', 'core'); ?></span></li>
									
									<?php if ($this->routeAccessor('core_role_list')) : ?>
									<li><a href="<?php echo $this->url(array(), 'core_role_list'); ?>"><?php echo $this->translator('menu_role', 'core'); ?></a></li>
									<?php endif; ?>
									
					                <?php if ($this->routeAccessor('core_user_list')) : ?>
									<li><a href="<?php echo $this->url(array(), 'core_user_list'); ?>"><?php echo $this->translator('menu_user', 'core'); ?></a></li>
									<?php endif; ?>
									
									<?php if ($this->routeAccessor('core_privilege_list')) : ?>
									<li><a href="<?php echo $this->url(array(), 'core_privilege_list'); ?>"><?php echo $this->translator('menu_privilege', 'core'); ?></a></li>
									<?php endif; ?>
					            </ul>
					            
					            <ul>
					                <li><span><?php echo $this->translator('menu_system_config', 'core'); ?></span></li>
					                
					                <?php if ($this->routeAccessor('core_language_list')) : ?>
									<li><a href="<?php echo $this->url(array(), 'core_language_list'); ?>"><?php echo $this->translator('menu_language', 'core'); ?></a></li>
									<?php endif; ?>
									
									<?php 
									/**
									 * @since 2.0.8
									 */
									?>
									<?php if ($this->routeAccessor('core_locale_config')) : ?>
									<li><a href="<?php echo $this->url(array(), 'core_locale_config'); ?>"><?php echo $this->translator('menu_locale', 'core'); ?></a></li>
									<?php endif; ?>
					                
					                <?php if ($this->routeAccessor('core_config_app')) : ?>
									<li><a href="<?php echo $this->url(array(), 'core_config_app'); ?>"><?php echo $this->translator('menu_config_app', 'core'); ?></a></li>
									<?php endif; ?>
					                
					                <?php if ($this->routeAccessor('core_config_list')) : ?>
									<li><a href="<?php echo $this->url(array(), 'core_config_list'); ?>"><?php echo $this->translator('menu_config', 'core'); ?></a></li>
									<?php endif; ?>
									
									<?php if ($this->routeAccessor('core_cache_list')) : ?>
									<li><a href="<?php echo $this->url(array(), 'core_cache_list'); ?>"><?php echo $this->translator('menu_cache', 'core'); ?></a></li>
									<?php endif; ?>
					                
					                <?php if ($this->routeAccessor('core_cache_config')) : ?>
									<li><a href="<?php echo $this->url(array(), 'core_cache_config'); ?>"><?php echo $this->translator('menu_cache_config', 'core'); ?></a></li>
									<?php endif; ?>
					            </ul>
					            
					            <ul>
					                <li><span><?php echo $this->translator('menu_custome', 'core'); ?></span></li>
					                
					                <?php if ($this->routeAccessor('core_template_list')) : ?>
									<li><a href="<?php echo $this->url(array(), 'core_template_list'); ?>"><?php echo $this->translator('menu_template', 'core'); ?></a></li>
									<?php endif; ?>
									
									<?php 
									/**
									 * Customize permalink
									 * @since 2.0.7
									 */
									?>
									<?php if ($this->routeAccessor('core_permalink_index')) : ?>
									<li><a href="<?php echo $this->url(array(), 'core_permalink_index'); ?>"><?php echo $this->translator('menu_permalink', 'core'); ?></a></li>
									<?php endif; ?>
					            </ul>
					            
					            <ul>
					                <li><span><?php echo $this->translator('menu_extend', 'core'); ?></span></li>
					                
					                <?php if ($this->routeAccessor('core_module_list')) : ?>
									<li><a href="<?php echo $this->url(array(), 'core_module_list'); ?>"><?php echo $this->translator('menu_module', 'core'); ?></a></li>
									<?php endif; ?>
									
					                <?php if ($this->routeAccessor('core_plugin_list')) : ?>
									<li><a href="<?php echo $this->url(array(), 'core_plugin_list'); ?>"><?php echo $this->translator('menu_plugin', 'core'); ?></a></li>
									<?php endif; ?>
					                
					                <?php if ($this->routeAccessor('core_widget_list')) : ?>
									<li><a href="<?php echo $this->url(array(), 'core_widget_list'); ?>"><?php echo $this->translator('menu_widget', 'core'); ?></a></li>
									<?php endif; ?>
					                
					                <?php if ($this->routeAccessor('core_hook_list')) : ?>
									<li><a href="<?php echo $this->url(array(), 'core_hook_list'); ?>"><?php echo $this->translator('menu_hook', 'core'); ?></a></li>
									<?php endif; ?>
					                
					                <?php if ($this->routeAccessor('core_target_list')) : ?>
									<li><a href="<?php echo $this->url(array(), 'core_target_list'); ?>"><?php echo $this->translator('menu_target', 'core'); ?></a></li>
									<?php endif; ?>
					            </ul>
					            
					            <div class="clearfix"><hr /></div>
					            
					            <ul>
					            	<li><span><?php echo $this->translator('menu_report', 'core'); ?></span></li>
					            	
					            	<?php 
					            	/**
					            	 * Errors log
					            	 * @since 2.0.7
					            	 */
					            	?>
					            	<?php if ($this->routeAccessor('core_log_list')) : ?>
					            	<li><a href="<?php echo $this->url(array(), 'core_log_list'); ?>"><?php echo $this->translator('menu_log', 'core'); ?></a></li>
					            	<?php endif; ?>
					            </ul>
				         	</div>
						</div>
					</li>
					
					<?php 
					/**
					 * Move all module administrator tasks to top menu
					 * @since 2.0.7
					 */ 
					 ?>
					<li>
						<a href="#"><?php echo $this->translator('menu_modules', 'core'); ?></a>
						
						<div class="sub">
							<div class="row">
								<?php foreach (($modules = $this->moduleTask()) as $index => $module) : ?>
								<?php if ($index % 4 == 0 & $index > 0) : ?><div class="clearfix"><hr /></div><?php endif; ?>
								<ul>
									<li><span><?php echo $module['description']; ?></span></li>
									
									<?php foreach ($module['tasks'] as $task) : ?>
									<li><a href="<?php echo $task['link']; ?>"><?php echo $task['label']; ?></a></li>
									<?php endforeach; ?>
								</ul>
								<?php endforeach; ?>
		                	</div>
		                </div>    
					</li>
					
					<li>
						<a href="#"><?php echo $this->translator('menu_account', 'core'); ?></a>
						
						<div class="sub" style="width: 140px !important; left: 0px">
							<div class="row">
		                     	<ul>
									<li><a href="<?php echo $this->url(array(), 'core_user_changepass'); ?>"><?php echo $this->translator('menu_changepass', 'core'); ?></a></li>
								</ul>
							</div>
						</div>
					</li>
				</ul>
			</div>