<?php 
/**
 * AmanCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@amancms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2010-2012 KhanSoft Limited (http://www.khansoft.com)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: config.phtml 4783 2010-08-23 10:41:16Z mehrab $
 * @since		2.0.6
 */
?>
<?php 
$this->headTitle($this->translator('cache_config_title'));
?>

<div class="flat_area grid_16 clearfix">
	<h2><a href="<?php echo $this->url(array(), 'core_cache_list'); ?>"><?php echo $this->translator('cache_list_breadcrumb'); ?></a></h2>	
</div>

<div class="grid_16"><?php echo $this->flashMessenger(); ?></div>

<form method="post" action="<?php echo $this->url(array(), 'core_cache_config'); ?>">
<div class="box grid_16">
	<div class="block lines">
		<div class="section"><?php echo $this->translator('cache_config_page_guide'); ?></div>
		<!-- Cache entire pages -->
		<div class="columns clearfix">
			<div class="col_50">
				<div class="section"><?php echo $this->translator('cache_config_page'); ?></div>
			</div>
			<div class="col_50">
				<div class="section"><?php echo $this->translator('cache_config_lifetime'); ?></div>
			</div>
		</div>
		<?php foreach ($this->pages as $page) : ?>
		<div class="columns clearfix">
			<div class="col_50">
				<div class="section">
					<input type="checkbox" name="selectedPages[]" value="<?php echo $page['page']->route; ?>" <?php if ($page['cache']['enable'] == 'true') : ?>checked="checked" <?php endif; ?>/> <?php echo $page['page']->title; ?>
				</div>
			</div>
			<div class="col_50">
				<div class="section">
					<input type="text" name="lifetime[<?php echo $page['page']->route; ?>]" value="<?php echo $page['cache']['lifetime']; ?>" <?php if ($page['cache']['enable'] != 'true') : ?>disabled="disabled" <?php endif; ?>style="width: 100px" />
				</div>
			</div>
		</div>
		<?php endforeach; ?>
		
		<br /><br />
		<!-- Compress configurations -->
		<ul class="flat">
			<li><?php echo $this->translator('cache_config_compress'); ?></li>
			<li><input type="checkbox" name="compressCss" value="1" <?php if ($this->compressCss == 'true') : ?> checked="checked"<?php endif; ?>/> <?php echo $this->translator('cache_config_compress_css'); ?></li>
			<li><input type="checkbox" name="compressJs" value="1" <?php if ($this->compressJs == 'true') : ?> checked="checked"<?php endif; ?>/> <?php echo $this->translator('cache_config_compress_javascript'); ?></li>
			<li><input type="checkbox" name="compressHtml" value="1" <?php if ($this->compressHtml == 'true') : ?> checked="checked"<?php endif; ?>/> <?php echo $this->translator('cache_config_compress_html'); ?></li>
		</ul>
		<div class="button_bar clearfix">
			<button type="submit"><span><?php echo $this->translator('cache_config_save'); ?></span></button>
		</div>
	</div>
</div>
</form>

<script type="text/javascript">
$(document).ready(function() {
	$('input[name="selectedPages[]"]').change(function() {
		var pageName = $(this).val();
		var lifetimeInput = $(this).parents('.t_a_ui_data_list_content').find('input[name="lifetime[' + pageName + ']"]:first');
		if ($(this).attr('checked') == 'checked' || $(this).attr('checked') == true) {
			$(lifetimeInput).removeAttr('disabled').focus();
		} else {
			$(lifetimeInput).attr('disabled', 'disabled');
		}
	});
});
</script>
