<?php 
/**
 * AmanCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@amancms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2010-2012 KhanSoft Limited (http://www.khansoft.com)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: list.phtml 4185 2010-08-01 16:31:02Z mehrab $
 * @since		1.0.0
 */
?>
<?php 
$this->headTitle($this->translator('cache_list_page_title'));

?>

<div class="flat_area grid_16 clearfix">
	<h2><?php echo $this->translator('cache_list_breadcrumb'); ?></h2>	
</div>

<!-- Left column -->
<div class="box grid_16 clearfix">
	<h2 class="box_head"><?php echo $this->translator('cache_list_info'); ?></h2>
	<div class="block">		
			<?php if (null == $this->cache) : ?>
				<?php echo $this->translator('cache_list_type'); ?>: <?php echo $this->translator('cache_list_not_used'); ?>
			<?php else : ?>
				<ul class="flat">
					<li><?php echo $this->translator('cache_list_type'); ?>: <?php echo $this->backend; ?></li>
					<li><?php echo $this->translator('cache_list_filling_percentage'); ?>: <?php if ($this->fillingPercentage) : ?><?php echo $this->fillingPercentage; ?>%<?php else : ?><?php echo $this->translator('cache_list_not_support_filling_percentage'); ?><?php endif; ?></li>
				</ul>	
				<?php if ($this->allow('clear')) : ?>
				<div class="button_bar clearfix">
					<button type="button" onclick="javascript: clearCache(this, 'data');" class="dark text_only has_text ">
						<span><?php echo $this->translator('cache_list_clear_cache_action'); ?></span>
					</button>
				</div>
				<?php endif; ?>
			<?php endif; ?>
	</div>
</div>
<div class="clear"></div>
<!-- Right column -->
<div class="box grid_16 tabs clearfix">	
	<ul id="cacheTabs" class="tab_header clearfix">
		<li><a href="#dataCached"><?php echo $this->translator('cache_list_data_cached'); ?></a></li>
		<li><a href="#filesCached"><?php echo $this->translator('cache_list_files_cached'); ?></a></li>
	</ul>
	<div class="controls">
		<a href="#" class="toggle"></a>
		<a href="#" class="show_all_tabs"></a>
	</div>
	<div class="toggle_container">
		<!-- Data cached -->
		<div id="dataCached" class="block">
			<?php if (null == $this->cache) : ?>
				<?php echo $this->translator('cache_list_not_found'); ?>
			<?php elseif ($this->supportListIds == false || $this->supportTags == false) : ?>
				<?php echo $this->translator('cache_list_not_support_tags'); ?>
			<?php elseif ($this->tags) : ?>
			<div id="cachedContainer" >
				<div class="section">
					<strong><?php echo $this->translator('cache_list_guide'); ?></strong><br />
					
					<div class="grid_3 alpha"><?php echo $this->translator('cache_list_id'); ?></div>
					<div class="grid_10"><?php echo $this->translator('cache_list_value_dump'); ?></div>
					<div class="grid_3 omega"><?php echo $this->translator('cache_list_action'); ?></div>
				</div>
				
				<!-- List cached data by tag -->
				<?php foreach ($this->tags as $tag) : ?>
				<div id="tagContainer_<?php echo $tag; ?>" class="section">
					<div class="grid_3 alpha">
						<?php echo $this->translator('cache_list_tag'); ?>: <a href="javascript: void(0);" class="collapseAction" id="<?php echo $tag; ?>"><?php echo $tag; ?></a>
					</div>
					<div class="grid_10">
						<?php if ($ids = $this->cacheIds[$tag]) : ?>(<?php echo sprintf($this->translator('cache_list_tag_num_items'), count($ids)); ?>)<?php endif; ?>
					</div>
					<div class="grid_2 omega">
						<?php if ($allowDelete = $this->allow('delete')) : ?><a class="deleteTagAction t_a_ui_helper_action" rel="<?php echo $this->escape($tag); ?>" href="javascript: void(0);"><?php echo $this->translator('cache_list_action_delete'); ?></a><?php endif; ?>
					</div>
				
					<?php if ($ids) : ?>
					<div class="clearfix" id="tagRow_<?php echo $tag; ?>"  style="display: none">
						<?php foreach ($ids as $id) : ?>
						<div id="cacheRow_<?php echo $id; ?>" class="clearfix section">
							<pre>	<?php echo $id; ?></pre>
							<textarea style="overflow-x: hidden; overflow-y: scroll; height:100px" class="grid_14" >
								<?php Zend_Debug::dump($this->cache->load($id)); ?>
							</textarea>
							<?php if ($allowDelete): ?><a class="deleteAction t_a_ui_helper_action" rel="<?php echo $this->escape($id); ?>" href="javascript: void(0);"><?php echo $this->translator('cache_list_action_delete'); ?></a><?php endif; ?>
						</div>
						<?php endforeach; ?>
					</div>
					<?php endif; ?>
				</div>
				<?php endforeach; ?>
			</div>
			<?php endif; ?>
		</div>
		
		<!-- Files cached -->
		<div id="filesCached" class="block">
			<!-- CSS cached -->
			<ul class="flat">
				<li>
					<div class="section">
						<h3><?php echo $this->translator('cache_list_css_cached'); ?></h3><br />
				
						<p>
							<?php if ($this->cssCached['numberFiles'] == 0) : ?>
							<?php echo $this->translator('cache_list_css_cached_not_available'); ?>
							<?php else : ?>
							<div class="section">
								<?php echo sprintf($this->translator('cache_list_css_cached_statistic'), $this->cssCached['numberFiles'], $this->sizeFormatter($this->cssCached['size'])); ?>
							</div>
							
							<?php if ($this->allow('clear')) : ?>
							<button type="button" onclick="javascript: clearCache(this, 'css');"><span><?php echo $this->translator('cache_list_clear_cache_action'); ?></span></button>
							<?php endif; ?>
							<?php endif; ?>
						</p>
					</div>
				
				</li>
				<li>
					<!-- Javascript cached -->
					<div class="section">
						<h3><?php echo $this->translator('cache_list_javascript_cached'); ?></h3>						
						<p>
							<?php if ($this->jsCached['numberFiles'] == 0) : ?>
							<?php echo $this->translator('cache_list_javascript_cached_not_available'); ?>
							<?php else : ?>
							<div class="section">
								<?php echo sprintf($this->translator('cache_list_javascript_cached_statistic'), $this->jsCached['numberFiles'], $this->sizeFormatter($this->jsCached['size'])); ?>
							</div>
							
							<?php if ($this->allow('clear')) : ?>
							<button type="button" onclick="javascript: clearCache(this, 'js');"><span><?php echo $this->translator('cache_list_clear_cache_action'); ?></span></button>
							<?php endif; ?>
							<?php endif; ?>
						</p>
					</div>
				</li>
				<li>
					<!-- HTML cached -->
					<div class="section">						
						<h3><?php echo $this->translator('cache_list_pages_cached'); ?></h3>
						<p>
							<?php if ($this->pagesCached['numberFiles'] == 0) : ?>
							<?php echo $this->translator('cache_list_pages_cached_not_available'); ?>
							<?php else : ?>
							<div class="t_a_bottom">
								<?php echo sprintf($this->translator('cache_list_pages_cached_statistic'), $this->pagesCached['numberFiles'], $this->sizeFormatter($this->pagesCached['size'])); ?>
							</div>
							
							<?php if ($this->allow('clear')) : ?>
							<button type="button" onclick="javascript: clearCache(this, 'pages');"><span><?php echo $this->translator('cache_list_clear_cache_action'); ?></span></button>
							<?php endif; ?>
							<?php endif; ?>
						</p>
					</div>
				</li>
			</ul>			
		</div>
	</div>
</div>

<div id="messageDialog"></div>

<div id="confirmDialog"></div>
		
<script type="text/javascript">
<?php if ($this->allow('clear')) : ?>
function clearCache(link, type) {
	$('#confirmDialog').html('<?php echo addslashes($this->translator('cache_list_clear_cache_confirm')); ?>')
		.dialog({
			title: '<?php echo addslashes($this->translator('common_dialog_confirm')); ?>',
			dialogClass: 't_a_ui_dialog',
			modal: true,
			closeOnEscape: false,
			resizable: false,
			open: function(event, ui) {
				$('.ui-dialog-titlebar-close').hide();
				$(this).parent().find('.ui-dialog-buttonpane button').wrapInner('<span/>');
			},
			buttons: {
				'<?php echo addslashes($this->translator('common_dialog_confirm_no')); ?>': function() {
					$(this).dialog('destroy');
				},
				'<?php echo addslashes($this->translator('common_dialog_confirm_yes')); ?>': function() {
					$(this).dialog('destroy');
					$(link).html('').addClass('t_a_ui_helper_loading');
					$.ajaxq('core_cache', {
						type: 'POST',
						url: "<?php echo $this->url(array(), 'core_cache_clear'); ?>",
						data: { type: type },
						success: function(response) {
							$(link).removeClass('t_a_ui_helper_loading').append($('<span/>').html('<?php echo addslashes($this->translator('cache_list_clear_cache_action')); ?>'));
							
							switch (type) {
								case 'data':
									$('#cachedContainer').html('<?php echo addslashes($this->translator('cache_list_empty')); ?>');
									break;
								case 'css':
									$(link).parent().html('<?php echo addslashes($this->translator('cache_list_css_cached_not_available')); ?>');
									break;
								case 'js':
									$(link).parent().html('<?php echo addslashes($this->translator('cache_list_javascript_cached_not_available')); ?>');
									break;
								case 'pages':
									$(link).parent().html('<?php echo addslashes($this->translator('cache_list_pages_cached_not_available')); ?>');
									break;
							}
							
							$('#messageDialog').html('<?php echo addslashes($this->translator('cache_list_clear_cache_success')); ?>')
								.dialog({
									title: '<?php echo addslashes($this->translator('common_dialog_message')); ?>',
									dialogClass: 't_a_ui_dialog',
									modal: true,
							    	show: { effect: 'fade' },
									open: function(event, ui) {
										setTimeout(function() {
											$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
										}, 3000);
									}
								});
						}
					});
				}
			}
		});
};
<?php endif; ?>

$(document).ready(function() {
	/**
	 * Create tabs
	 */
	$('#cacheTabs').tabs();
	
	$('a.collapseAction').click(function() {
		$('#tagRow_' + $(this).attr('id')).toggle();
	});
	
	<?php if (isset($allowDelete) && $allowDelete == true) : ?>
	$('.deleteTagAction').click(function() {
		var self = this;
		
		$('#confirmDialog').html('<?php echo addslashes($this->translator('cache_list_delete_tag_confirm')); ?>')
			.dialog({
				title: '<?php echo addslashes($this->translator('common_dialog_confirm')); ?>',
				dialogClass: 't_a_ui_dialog',
				modal: true,
				closeOnEscape: false,
				resizable: false,
				open: function(event, ui) {
					$('.ui-dialog-titlebar-close').hide();
					$(this).parent().find('.ui-dialog-buttonpane button').wrapInner('<span/>');
				},
				buttons: {
					'<?php echo addslashes($this->translator('common_dialog_confirm_no')); ?>': function() {
						$(this).dialog('destroy');
					},
					'<?php echo addslashes($this->translator('common_dialog_confirm_yes')); ?>': function() {
						$(this).dialog('destroy');
						$(self).html('').addClass('t_a_ui_helper_loading');
						var tag = $(self).attr('rel');
						$.ajaxq('core_cache', {
							type: 'POST',
							url: "<?php echo $this->url(array(), 'core_cache_delete'); ?>",
							data: { type: 'tag', id: tag },
							success: function(response) {
								$('#tagContainer_' + tag).remove();
								$('#messageDialog').html(sprintf('<?php echo addslashes($this->translator('cache_list_delete_tag_success')); ?>', tag.substring(0, 30) + '...'))
									.dialog({
										title: '<?php echo addslashes($this->translator('common_dialog_message')); ?>',
										dialogClass: 't_a_ui_dialog',
										modal: true,
								    	show: { effect: 'fade' },
										open: function(event, ui) {
											setTimeout(function() {
												$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
											}, 3000);
										}
									});
							}
						});
					}
				}
			});
	});
	
	$('a.deleteAction').click(function() {
		var self = this;
		$('#confirmDialog').html('<?php echo addslashes($this->translator('cache_list_delete_confirm')); ?>')
			.dialog({
				title: '<?php echo addslashes($this->translator('common_dialog_confirm')); ?>',
				dialogClass: 't_a_ui_dialog',
				modal: true,
				closeOnEscape: false,
				resizable: false,
				open: function(event, ui) {
					$('.ui-dialog-titlebar-close').hide();
					$(this).parent().find('.ui-dialog-buttonpane button').wrapInner('<span/>');
				},
				buttons: {
					'<?php echo addslashes($this->translator('common_dialog_confirm_no')); ?>': function() {
						$(this).dialog('destroy');
					},
					'<?php echo addslashes($this->translator('common_dialog_confirm_yes')); ?>': function() {
						$(this).dialog('destroy');
						$(self).html('').addClass('t_a_ui_helper_loading');
						var id = $(self).attr('rel');
						$.ajaxq('core_cache', {
							type: 'POST',
							url: "<?php echo $this->url(array(), 'core_cache_delete'); ?>",
							data: { type: 'id', id: id },
							success: function(response) {
								$('#cacheRow_' + id).fadeOut();
								$('#messageDialog').html(sprintf('<?php echo addslashes($this->translator('cache_list_delete_success')); ?>', id.substring(0, 30) + '...'))
									.dialog({
										title: '<?php echo addslashes($this->translator('common_dialog_message')); ?>',
										dialogClass: 't_a_ui_dialog',
										modal: true,
								    	show: { effect: 'fade' },
										open: function(event, ui) {
											setTimeout(function() {
												$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
											}, 3000);
										}
									});
							}
						});
					}
				}
			});
	});
	<?php endif; ?>	
});
</script>
